name: Terraform CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
  
    defaults:
      run:
        working-directory: terraform

      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "eu-west-1"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Initialize Terraform
        run: terraform init

      - name: Validate Terraform configuration
        run: terraform validate

      - name: Plan Terraform changes
        run: terraform plan -out=tfplan

      - name: Apply Terraform changes
        run: terraform apply -auto-approve tfplan

      - name: Wait for EC2 instance
        run: |
          echo "Waiting for EC2 instance to be ready..."
          sleep 60

      - name: Fetch public IP
        id: ec2_ip
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "PUBLIC_IP=$PUBLIC_IP" >> $GITHUB_OUTPUT

      - name: Health check
        run: curl -f http://${{ steps.ec2_ip.outputs.public_ip }} || (echo "Instance not responding" && exit 1)

      - name: Keep instance running
        run: |
          echo "Instance running for 5 minutes at: ${{ steps.ec2_ip.outputs.public_ip }}"
          sleep 300

      - name: Destroy Terraform resources
        if: always()
        run: terraform destroy -auto-approve